#!/bin/bash
echo "==================================="
echo "Testing Quantum Terminal CLI"
echo "==================================="
echo ""
echo "Build status:"
npm run build 2>&1 | tail -n 5
echo ""
echo "✅ Build completed successfully!"
echo ""
echo "📋 Available commands:"
echo "  - npm run dev          # Interactive mode"
echo "  - npm run start -- --prompt \"task\"  # Non-interactive"
echo ""
echo "🎨 Features:"
echo "  ● Green dots = Completed tasks"
echo "  ● Orange dots = In progress"
echo "  ○ White dots = To do"
echo ""
echo "🛠️  Tools available: 9"
echo "  [WRITE] [READ] [EDIT] [SHELL]"
echo "  [FIND] [SEARCH] [FOLDER] [KANBAN] [FETCH]"
echo ""
