export const mockUser = {
  id: 'user-1',
  name: 'John Doe',
  email: 'john.doe@example.com',
  avatar: 'https://via.placeholder.com/40x40',
  plan: 'premium',
};

export const mockPlaylists = [
  {
    id: 'playlist-1',
    name: 'My Favorites',
    description: 'My favorite tracks',
    coverImage: 'https://via.placeholder.com/300x300',
    tracks: ['track-1', 'track-2', 'track-3'],
    owner: 'John Doe',
    duration: '2h 15m',
    trackCount: 15,
  },
  {
    id: 'playlist-2',
    name: 'Chill Vibes',
    description: 'Relaxing music for your day',
    coverImage: 'https://via.placeholder.com/300x300',
    tracks: ['track-4', 'track-5', 'track-6'],
    owner: 'John Doe',
    duration: '1h 42m',
    trackCount: 12,
  },
  {
    id: 'playlist-3',
    name: 'Workout Mix',
    description: 'High energy tracks for your workout',
    coverImage: 'https://via.placeholder.com/300x300',
    tracks: ['track-7', 'track-8', 'track-9'],
    owner: 'John Doe',
    duration: '1h 30m',
    trackCount: 10,
  },
];

export const mockTracks = [
  {
    id: 'track-1',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: '3:20',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track1.mp3',
    genre: 'Synth-pop',
    releaseYear: 2020,
  },
  {
    id: 'track-2',
    title: 'Save Your Tears',
    artist: 'The Weeknd',
    album: 'After Hours',
    duration: '3:35',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track2.mp3',
    genre: 'Synth-pop',
    releaseYear: 2020,
  },
  {
    id: 'track-3',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: '3:23',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track3.mp3',
    genre: 'Disco-pop',
    releaseYear: 2020,
  },
  {
    id: 'track-4',
    title: 'Watermelon Sugar',
    artist: 'Harry Styles',
    album: 'Fine Line',
    duration: '2:54',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track4.mp3',
    genre: 'Pop rock',
    releaseYear: 2019,
  },
  {
    id: 'track-5',
    title: 'Don\'t Start Now',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    duration: '3:03',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track5.mp3',
    genre: 'Disco-pop',
    releaseYear: 2019,
  },
  {
    id: 'track-6',
    title: 'Adore You',
    artist: 'Harry Styles',
    album: 'Fine Line',
    duration: '3:27',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track6.mp3',
    genre: 'Pop rock',
    releaseYear: 2019,
  },
  {
    id: 'track-7',
    title: 'Dynamite',
    artist: 'BTS',
    album: 'Dynamite (Single)',
    duration: '3:19',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track7.mp3',
    genre: 'Disco-pop',
    releaseYear: 2020,
  },
  {
    id: 'track-8',
    title: 'Life Is Good',
    artist: 'Future ft. Drake',
    album: 'High Off Life',
    duration: '4:07',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track8.mp3',
    genre: 'Hip-hop',
    releaseYear: 2020,
  },
  {
    id: 'track-9',
    title: 'Mood',
    artist: '24kGoldn ft. Iann Dior',
    album: 'El Dorado',
    duration: '2:49',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track9.mp3',
    genre: 'Hip-hop',
    releaseYear: 2020,
  },
  {
    id: 'track-10',
    title: 'Positions',
    artist: 'Ariana Grande',
    album: 'Positions',
    duration: '2:52',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track10.mp3',
    genre: 'Pop',
    releaseYear: 2020,
  },
  {
    id: 'track-11',
    title: 'Holy',
    artist: 'Justin Bieber ft. Chance the Rapper',
    album: 'Justice',
    duration: '3:13',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track11.mp3',
    genre: 'Pop',
    releaseYear: 2021,
  },
  {
    id: 'track-12',
    title: 'Therefore I Am',
    artist: 'Billie Eilish',
    album: 'Happier Than Ever',
    duration: '2:53',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track12.mp3',
    genre: 'Pop',
    releaseYear: 2021,
  },
  {
    id: 'track-13',
    title: 'Good Days',
    artist: 'SZA',
    album: 'Good Days (Single)',
    duration: '4:38',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track13.mp3',
    genre: 'R&B',
    releaseYear: 2020,
  },
  {
    id: 'track-14',
    title: '34+35',
    artist: 'Ariana Grande',
    album: 'Positions',
    duration: '3:02',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track14.mp3',
    genre: 'Pop',
    releaseYear: 2020,
  },
  {
    id: 'track-15',
    title: 'Wants and Needs',
    artist: 'Drake ft. Lil Baby',
    album: 'Scary Hours 2',
    duration: '3:49',
    coverImage: 'https://via.placeholder.com/300x300',
    audioUrl: '/audio/track15.mp3',
    genre: 'Hip-hop',
    releaseYear: 2021,
  },
];